org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=320m -XX:ReservedCodeCacheSize=128m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
android.builder.sdkDownload=false
kotlin.code.style=official
# 指定构建输出目录相对于项目根目录的路径
org.gradle.project.buildDir=app/

